// Creates the admin-first status, next-action, and contact summary for a student account.
export function GhtAdminSummary({ ghtStudent, ghtFormatNaira }) {
  const ghtHasBalance = ghtStudent.summary.outstanding > 0;
  const ghtCompletion = ghtStudent.summary.payable ? Math.round((ghtStudent.summary.paid / ghtStudent.summary.payable) * 100) : 100;
  const ghtStatusLabel = ghtHasBalance ? `${ghtFormatNaira(ghtStudent.summary.outstanding)} due` : 'Paid in full';
  const ghtNextStep = ghtHasBalance ? 'Contact the guardian about the remaining balance.' : 'No payment is due for this term.';
  const ghtTone = ghtHasBalance ? 'accent' : 'success';
  const ghtSummary = document.createElement('section');
  ghtSummary.className = 'ght-admin-summary grid gap-4 lg:grid-cols-[1.1fr_.9fr]';
  ghtSummary.innerHTML = `<section class="ght-card ght-attention-card ${ghtHasBalance ? 'ght-attention-card--pending' : 'ght-attention-card--clear'}"><div class="flex items-start justify-between gap-4"><div><p class="m-0 text-xs font-semibold uppercase tracking-[.08em] text-[#737373]">Admin attention</p><h2 class="m-0 mt-2 text-2xl font-medium tracking-[-.5px]">${ghtHasBalance ? 'Payment follow-up needed.' : 'Everything is up to date.'}</h2></div><div class="ght-attention-mark" aria-hidden="true">${ghtHasBalance ? '!' : '✓'}</div></div><p class="mb-0 mt-3 max-w-xl text-sm leading-6 text-[#525252]">${ghtNextStep}</p><div class="mt-6 flex flex-wrap items-center gap-3"><span class="ght-chip ght-chip--${ghtTone}">${ghtStatusLabel}</span><span class="text-xs text-[#737373]">${ghtCompletion}% of payable fees covered</span></div><div class="ght-progress-track mt-4"><div class="ght-progress-fill" style="width: ${Math.min(ghtCompletion, 100)}%"></div></div></section><section class="ght-card"><div class="flex items-start justify-between gap-3"><div><p class="m-0 text-xs font-semibold uppercase tracking-[.08em] text-[#737373]">Primary contact</p><h2 class="m-0 mt-2 text-xl font-medium tracking-[-.4px]">${ghtStudent.guardian}</h2></div><span class="ght-empty-orb flex items-center justify-center text-[#915239]" aria-hidden="true"><svg viewBox="0 0 24 24" class="h-4 w-4" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 21a8 8 0 0 0-16 0M12 13a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z"/></svg></span></div><dl class="ght-summary-details mt-5"><div><dt>Relationship</dt><dd>Guardian</dd></div><div><dt>Student ID</dt><dd>${ghtStudent.studentNumber}</dd></div><div><dt>Class</dt><dd>${ghtStudent.className}</dd></div><div><dt>Account status</dt><dd>${ghtStudent.accountStatus}</dd></div></dl></section></section>`;
  ghtSummary.innerHTML = ghtSummary.innerHTML.replace('Admin attention', 'Payment status').replace('Payment follow-up needed.', 'Payment needed.').replace('Everything is up to date.', 'Paid in full.').replace('Follow up with the guardian before the next collection review.', 'Contact the guardian about the remaining balance.').replace('Account settled', 'Paid in full').replace('outstanding', 'due');
  Object.defineProperty(ghtSummary, 'toString', { value: () => ghtSummary.outerHTML });
  return ghtSummary;
}
